### ISSUE TITLE
The exercise 2 is not complete yet!

### ISSUE THREAD

**Issue by D3W10** [D3W10/ISEL-SO#11]
The second exercise of trab3 is not complete, the developed functions appear to be unused. Perhaps the `main` function needs some rethinking?

Here's a list of all unused functions:
```
int reserveChargePoint(ChargePoint *point)

void freeChargePoint(ChargePoint *point, int lugar)

int reserveChargePointPriority(ChargePoint *point)
```

Consider fixing this issue asap and lmk so I can close it.

**Comment by d3xeldev** [comment]
A fix is currently being worked on
